name: 1.4$(Rev:.r)
resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604
  demands: 
  - npm
  - DotNetFramework

steps:
- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
  displayName: 'Use Yarn 1.x'
  inputs:
    checkLatest: true

- task: CacheBeta@0
  inputs:
    key: |
      yarn
      $(Build.SourcesDirectory)/yarn.lock
    path: $(Pipeline.Workspace)/.yarn
  displayName: Cache Yarn packages

- script: 'yarn install --frozen-lockfile' 
  displayName: 'Run yarn install'

- script: 'yarn prepextension' 
  displayName: 'Run yarn prepextension'
  workingDirectory: '$(Build.SourcesDirectory)'

- task: PublishTestResults@2
  displayName: 'Publish Test Results test-results.xml'
  inputs:
    testResultsFiles: '$(Build.SourcesDirectory)/test-results.xml'
    testRunTitle: 'Publish test results'
  condition: succeededOrFailed()

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage Results $(Build.SourcesDirectory)/coverage/cobertura-coverage.xml'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/coverage/cobertura-coverage.xml'
    reportDirectory: '$(Build.SourcesDirectory)/coverage'

- task: ms-devlabs.vsts-developer-tools-build-tasks.package-extension-build-task.PackageVSTSExtension@1
  displayName: 'Package real Extension '
  inputs:
    rootFolder: '$(Build.SourcesDirectory)'
    outputPath: '$(Build.ArtifactStagingDirectory)/colinsalmcorner.colinsalmcorner-buildtasks-$(Build.BuildNumber).vsix'
    publisherId: colinsalmcorner
    extensionId: 'colinsalmcorner-buildtasks'
    extensionVersion: '$(Build.BuildNumber)'
    updateTasksVersion: true
    updateTasksVersionType: patch
    cwd: '$(Build.SourcesDirectory)'

- powershell: './Update-TaskIDs.ps1 -Beta'
  displayName: 'PowerShell Update beta ids'
  condition: eq(variables['Agent.OS'], 'Windows_NT')
  failOnStderr: true

- bash: 'sh update-taskids.sh beta' 
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Bash Update beta ids'
  condition: ne(variables['Agent.OS'], 'Windows_NT')
  failOnStderr: true

- task: ms-devlabs.vsts-developer-tools-build-tasks.package-extension-build-task.PackageVSTSExtension@1
  displayName: 'Package beta Extension '
  inputs:
    outputPath: '$(Build.ArtifactStagingDirectory)/colinsalmcorner.colinsalmcorner-buildtasks-beta-$(Build.BuildNumber).vsix'
    publisherId: colinsalmcorner
    extensionId: 'colinsalmcorner-buildtasks'
    extensionTag: beta
    extensionVersion: '$(Build.BuildNumber)'
    updateTasksVersion: true
    updateTasksVersionType: patch
    extensionVisibility: private
    extensionPricing: free

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: vsix'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: vsix